=== EVERSE-ResearchSoftware/indicators/tests/indicator_validation_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Software Quality Indicator",
    "type": "object",
    "properties": {
        "@context": {
            "type": "string",
            "const": "https://w3id.org/everse/rsqi#"
        },
        "@id": {
            "type": "string",
            "format": "uri"
        },
        "@type": {
            "type": "string",
            "description": "The type of the quality indicator."
        },
        "name": {
            "type": "string",
            "description": "The name of the quality indicator."
        },
        "abbreviation": {
            "type": "string",
            "description": "Abbreviation or short form of the indicator name."
        },
        "alternateName": {
            "type": "string",
            "description": "Alternate name available for the indicator."
        },
        "description": {
            "type": "string",
            "description": "A brief description of the quality indicator."
        },
        "author": {
            "oneOf": [
                {
                    "type": "object",
                    "description": "The author of the quality indicator.",
                    "properties": {
                        "@type": {
                            "type": "string",
                            "format": "uri"

                        },
                        "name": {
                            "type": "string"
                        },
                        "email": {
                            "type": "string",
                            "format": "email"
                        },
                        "url": {
                            "type": "string",
                            "format": "uri"
                        }
                    }
                },
                {
                    "type": "array",
                    "description": "Multiple authors of the quality indicator.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "@type": {
                                "type": "string",
                                "format": "uri"

                            },
                            "name": {
                                "type": "string"
                            },
                            "email": {
                                "type": "string",
                                "format": "email"
                            },
                            "url": {
                                "type": "string",
                                "format": "uri"
                            }
                        }
                    }
                }
            ]
        },
        "created": {
            "type": "string",
            "format": "date-time",
            "description": "The creation date of the quality indicator."
        },
        "version": {
            "type": "string",
            "description": "The version of the quality indicator."
        },
        "status": {
            "type": "string",
            "description": "The status of the quality indicator."
        },
        "keywords": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "Keywords associated with the quality indicator."
        },
        "identifier": {
            "type": "object",
            "description": "An identifier for the quality indicator.",
            "properties": {
                "@id": {
                    "type": "string",
                    "format": "uri"

                }
            }
        },
        "qualityDimension": {
            "oneOf": [
                {
                    "type": "object",
                    "description": "The quality dimension this indicator pertains to.",
                    "properties": {
                        "@id": {
                            "type": "string",
                            "format": "uri"

                        }
                    }
                },
                {
                    "type": "array",
                    "description": "Multiple quality dimensions this indicator pertains to.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "@id": {
                                "type": "string",
                                "format": "uri"

                            }
                        }
                    }
                }
            ]
        },
        "source": {
            "oneOf": [
                {
                    "type": "object",
                    "description": "The source from which this indicator is derived.",
                    "properties": {
                        "@id": {
                            "type": "string",
                            "format": "uri"

                        },
                        "identifier": {
                            "type": "string",
                            "format": "uri"
                        },
                        "@type": {
                            "type": "string"
                        },
                        "url": {
                            "type": "string",
                            "format": "uri"
                        },
                        "name": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "name"
                    ]
                },
                {
                    "type": "array",
                    "description": "Multiple sources from which this indicator is derived.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "@id": {
                                "type": "string",
                                "format": "uri"

                            },
                            "identifier": {
                                "type": "string",
                                "format": "uri"
                            },
                            "@type": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string",
                                "format": "uri"
                            },
                            "name": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name"
                        ]
                    }
                }
            ]
        },
        "contact": {
            "oneOf": [
                {
                    "type": "object",
                    "description": "Contact point for more information.",
                    "properties": {
                        "@type": {
                            "type": "string",
                            "format": "uri"
                        },
                        "name": {
                            "type": "string"
                        },
                        "email": {
                            "type": "string",
                            "format": "email"
                        }
                    }
                },
                {
                    "type": "array",
                    "description": "Multiple contact points for more information.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "@type": {
                                "type": "string",
                                "format": "uri"
                            },
                            "name": {
                                "type": "string"
                            },
                            "email": {
                                "type": "string",
                                "format": "email"
                            }
                        }
                    }
                }
            ]
        },
        "contactPoint": {
            "oneOf": [
                {
                    "type": "object",
                    "description": "Contact point for more information.",
                    "properties": {
                        "@type": {
                            "type": "string",
                            "format": "uri"
                        },
                "name": {
                            "type": "string"
                        },
                        "email": {
                            "type": "string",
                            "format": "email"
                        }
                    }
                },
                {
                    "type": "array",
                    "description": "Multiple contact points for more information.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "@type": {
                                "type": "string",
                                "format": "uri"
                            },
                            "name": {
                                "type": "string"
                            },
                            "email": {
                                "type": "string",
                                "format": "email"
                            }
                        }
                    }
                }
            ]
        },
        "sameAs": {
            "type": "string",
            "format": "uri",
            "description": "URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website."
        }
    },
    "required": [
        "@context",
        "@type",
        "name",
        "abbreviation",
        "description",
        "contact",
        "version",
        "identifier",
        "qualityDimension"
    ],
    "additionalProperties": false
}

=== EVERSE-ResearchSoftware/indicators/indicators/has_license.json
{
    "@context": "https://w3id.org/everse/rsqi#",
    "@id": "https://w3id.org/everse/i/indicators/software_has_license",
    "@type": "SoftwareQualityIndicator",
    "name": "Software has license",
    "abbreviation": "software_has_license",
    "description": "This check tries to determine if the project has published a license",
    "alternateName": "FRSM-15",
    "keywords": [ "license", "metadata", "fair" ],
    "identifier": { "@id": "https://w3id.org/everse/i/indicators/software_has_license" },
    "status": "Active",
    "version": "1.0.0",
    "author" : {
        "@type" : "schema:Organization",
        "name" : "OpenSSF",
        "url" : "https://openssf.org/"
    },
    "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
    "source": [
        {
            "url": "https://github.com/ossf/scorecard/blob/cd152cb6742c5b8f2f3d2b5193b41d9c50905198/docs/checks.md#license",
            "name": "OpenSSF Scorecard: License"
        },
        {
            "url": "https://fair-impact.github.io/RSMD-guidelines/6.Reuse_legal/",
            "name": "Reuse, licensing and legal aspects. RSMD-6.2"
        }
    ],
    "qualityDimension": { "@id": "https://w3id.org/everse/i/dimensions/fairness" },
    "created": "23-05-2025"
}

=== EVERSE-ResearchSoftware/indicators/indicators/repository_workflows.json
{
    "@context": "https://w3id.org/everse/rsqi#",
    "@id": "https://w3id.org/everse/i/indicators/repository_workflows",
    "@type": "SoftwareQualityIndicator",
    "name": "Software has ci/cd workflows in its repository",
    "abbreviation": "repository_workflows",
    "description": "This indicator tries aims determine if a software project makes use of workflows to automatize processes like testing and deployment.",
    "keywords": [ "workflows", "github", "fair", "repository"],
    "identifier": { "@id": "https://w3id.org/everse/i/indicators/repository_workflows" },
    "status": "Active",
    "version": "1.0.0",
    "author" : {
        "@type" : "schema:Organization",
        "name" : "OpenSSF",
        "url" : "https://openssf.org/"
    },
    "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
    "source": [
        {
            "url": "https://github.com/ossf/scorecard/blob/cd152cb6742c5b8f2f3d2b5193b41d9c50905198/docs/checks.md#ci-tests",
            "name": "OpenSSF Scorecard: CI-Tests"
        }
    ],
    "qualityDimension": { "@id": "https://w3id.org/everse/i/dimensions/maintainability"},
    "created": "23-05-2025"
}

=== EVERSE-ResearchSoftware/indicators/indicators/software_has_tests.json
{
    "@context": "https://w3id.org/everse/rsqi#",
    "@id": "https://w3id.org/everse/i/indicators/software_has_tests",
    "@type": "SoftwareQualityIndicator",
    "name": "Software provides tests",
    "abbreviation": "software_has_tests",
    "alternateName": "FRSM-14",
    "description": "Evaluates the extent to which the software has been tested, including unit tests, integration tests, and system tests, to ensure reliability and correctness.",
    "keywords": [ "test", "functionality", "fair"],
    "identifier": { "@id": "https://w3id.org/everse/i/indicators/software_has_tests" },
    "sameAs": "https://doi.org/10.25504/FAIRsharing.a2dd1a",
    "status": "Active",
    "version": "1.0.0",
    "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
    "author" : {
        "@type" : "schema:Organization",
        "name" : "FAIR-IMPACT"
    },
    "source": {
        "url" : "https://zenodo.org/records/10047401",
        "name" : "D5.2 - Metrics for automated FAIR software assessment in a disciplinary context"
    },
    "qualityDimension": [
        { "@id": "https://w3id.org/everse/i/dimensions/fairness" },
        { "@id": "https://w3id.org/everse/i/dimensions/reliability" }
    ],
    "created": "23-05-2025"
}

=== EVERSE-ResearchSoftware/indicators/indicators/internal_cohesion_ok.json
{
  "@context": "https://w3id.org/everse/rsqi#",
  "@id": "https://w3id.org/everse/i/indicators/internal_cohesion_ok",
  "@type": "SoftwareQualityIndicator",
  "name": "Cohesion among methods/functions of a module follows community conventions",
  "abbreviation": "internal_cohesion_ok",
  "identifier": { "@id": "https://w3id.org/everse/i/indicators/internal_cohesion_ok" },
  "description": "The cohesion among methods/functions of a module is maintained to a reasonable level according to community expectations and standards. Cohesion describes how related the functions within a single module are. Low cohesion implies that a given module performs tasks which are not very related to each other and hence can create problems as the module becomes large.",
  "status": "Active",
  "keywords": [
    "maintainability", "cohesion", "module", "code"
  ],
  "version": "1.0.0",
  "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
  "source": [
    {
      "identifier": "https://zenodo.org/records/10647227",
      "url": "https://zenodo.org/records/10647227",
      "name": "Task Force Sub Group 3 - Review of Software Quality Attributes and Characteristics"
    },
    {
      "url": "https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=11216562&tag=1",
      "name": "Socially-Informed Jupyter Notebook Quality: A Role- and Lifecycle-Aware Metrics Framework"
    }
  ],
  "qualityDimension": { "@id": "https://w3id.org/everse/i/dimensions/maintainability" },
  "created": "11-03-2026"
}

=== EVERSE-ResearchSoftware/indicators/indicators/support_issue_tracking.json
{
    "@context": "https://w3id.org/everse/rsqi#",
    "@id": "https://w3id.org/everse/i/indicators/support_issue_tracking",
    "@type": "SoftwareQualityIndicator",
    "name": "Software provides issue tracking",
    "abbreviation": "support_issue_tracking",
    "description": "The software project offers an accessible issue tracking system (e.g., GitHub/GitLab Issues or a helpdesk) that is used to report, document, and manage bugs, enhancement requests, and user-facing operational issues.",
    "source": {
        "@id": "https://zenodo.org/records/17035105",
        "url": "https://zenodo.org/records/17035105",
        "name": "ELIXIR-STEERS D2.1 Report on best-practices and indicators available and used by selected Communities"
    },
    "keywords": ["support", "issues", "helpdesk", "maintenance", "user support"],
    "identifier": { "@id": "https://w3id.org/everse/i/indicators/support_issue_tracking"},
    "status": "Active",
    "version": "1.0.0",
    "author": {
        "@type": "Organization",
        "name": "OpenSSF",
        "url": "https://openssf.org/"
    },
    "contact": {
        "@type": "schema:Person",
        "name": "Federica Quaglia",
        "email": "federica.quaglia@unipd.it"
    },
    "qualityDimension": { "@id": "https://w3id.org/everse/i/dimensions/maintainability"},
    "created": "03-12-2025"
 }

=== EVERSE-ResearchSoftware/indicators/indicators/archived_in_scholarly_repository.json
{
    "@context": "https://w3id.org/everse/rsqi#",
    "@id": "https://w3id.org/everse/i/indicators/archived_in_scholarly_repository",
    "@type": "SoftwareQualityIndicator",
    "name": "Software is archived in a scholarly repository",
    "abbreviation": "archived_in_scholarly_repository",
    "description": "The source code repository is archived in a scholarly repository (e.g Zenodo, HAL) to ensure that software can be found and accessed in a scholarly context.",
    "source": {
        "@id": "https://fair-impact.github.io/RSMD-guidelines/8.rsmd_checklist/",
        "url": "https://fair-impact.github.io/RSMD-guidelines/8.rsmd_checklist/#accessibility-and-preservation",
        "name": "Accessibility and preservation. RSMD 2.2"
    },
    "keywords": ["repository", "fair", "scholar"],
    "identifier": { "@id": "https://w3id.org/everse/i/indicators/archived_in_scholarly_repository"},
    "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
    "status": "Active",
    "version": "1.0.0",
    "author" : {
        "@type" : "schema:Organization",
        "name" : "FAIR-IMPACT"
    },
    "qualityDimension": { "@id": "https://w3id.org/everse/i/dimensions/fairness" },
    "created": "23-06-2025"
  }

=== EVERSE-ResearchSoftware/indicators/indicators/human_code_review_requirement.json
{
    "@context": "https://w3id.org/everse/rsqi#",
    "@id": "https://w3id.org/everse/i/indicators/human_code_review_requirement",
    "@type": "SoftwareQualityIndicator",
    "name": "Software requires human code review.",
    "abbreviation": "human code review requirement",
    "description": "This indicator aims to determine if a software project requires human code review before pull requests.",
    "keywords": ["human-in-the-loop","pull request","review"],
    "identifier": { "@id": "https://w3id.org/everse/i/indicators/human_code_review_requirement" },
    "status": "Active",
    "version": "1.0.0",
    "author" : {
        "@type" : "schema:Organization",
        "name" : "OpenSSF",
        "url" : "https://openssf.org/"
    },
    "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
    "source": {
        "url": "https://github.com/ossf/scorecard/blob/cd152cb6742c5b8f2f3d2b5193b41d9c50905198/docs/checks.md#code-review",
        "name": "OpenSSF Scorecard: Code-Review"
    },
    "qualityDimension": { "@id": "https://w3id.org/everse/i/dimensions/functional_suitability" },
    "created": "23-05-2025"
}

=== EVERSE-ResearchSoftware/indicators/indicators/cyclomatic_complexity.json
{
  "@context": "https://w3id.org/everse/rsqi#",
  "@id": "https://w3id.org/everse/i/indicators/cyclomatic_complexity_ok",
  "@type": "SoftwareQualityIndicator",
  "name": "Cyclomatic complexity follows community conventions",
  "abbreviation": "cyclomatic_complexity_ok",
  "identifier": { "@id": "https://w3id.org/everse/i/indicators/cyclomatic_complexity_ok" },
  "description": "Cyclomatic complexity (i.e., the number of linearly independent paths through a program’s source code) of the whole software component or modules/components/classes/functions/methods should follow the conventions established by the community  responsible for maintaining the tool. Cyclomatic complexity is created by calculating the number of different code paths in the flow of the program. A program that has complex control flow requires more tests to achieve good code coverage and is less maintainable.",
  "status": "Active",
  "keywords": [
    "maintainability", "complexity, code"
  ],
  "version": "1.0.0",
  "author": {
    "@type": "schema:Person",
    "name": "Daniel Garijo"
  },
  "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
  "source": [
    {
      "identifier": "https://zenodo.org/records/10647227",
      "url": "https://zenodo.org/records/10647227",
      "name": "Task Force Sub Group 3 - Review of Software Quality Attributes and Characteristics"
    },
    {
      "url": "https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=11216562&tag=1",
      "name": "Socially-Informed Jupyter Notebook Quality: A Role- and Lifecycle-Aware Metrics Framework"
    }
  ],
  "qualityDimension": { "@id": "https://w3id.org/everse/i/dimensions/maintainability" },
  "created": "10-03-2026"
}
